Repository UKHomeOffice/hocs-mi-dashboards, pull requests merged in 2022-11, with the labels that each got.

#5 Some changes to PR so we can push the image to quay
  .github/workflows/docker-push.yml
  app/Dockerfile
Labels: major

#6 Move Dockerfile for the app to project root
  Dockerfile
  docker-compose.yml
Labels: major

#7 Set user in container
  Dockerfile
Labels: minor

#9 build-and-push image requires tests to pass first
  .github/workflows/docker-push.yml
Labels: patch

#12 update readme with details of drone pipeline
  README.md
Labels: minor

#13 Update submodule url & path to deploy script
  .drone.yml
  .gitmodules
Labels: minor

#17 Query dbt view
  app/index.py
Labels: patch
